#!/usr/bin/env bash
# Publishes a new version of the Homebrew cask to flexpa/homebrew-tap.
#
#   scripts/update-cask.sh <version> <dmg-sha256>
#
# Creates the tap repository on first run. Needs a token with repo scope on the
# tap in GH_TOKEN (CI uses the HOMEBREW_TAP_TOKEN secret; locally `gh auth` is enough).
set -euo pipefail

VERSION="${1:?usage: update-cask.sh <version> <dmg-sha256>}"
SHA256="${2:?usage: update-cask.sh <version> <dmg-sha256>}"
TAP="${HOMEBREW_TAP_REPO:-flexpa/homebrew-tap}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if ! gh repo view "$TAP" > /dev/null 2>&1; then
  echo "▸ creating $TAP"
  gh repo create "$TAP" --public \
    --description "Homebrew tap for Flexpa: brew install --cask flexpa/tap/flexpa-health-bridge"
  # A brand-new repo has no commits; seed one so the clone below works.
  git -C "$WORK" init -q seed
  (
    cd "$WORK/seed"
    cat > README.md <<'READme'
# Flexpa Homebrew tap

```sh
brew tap flexpa/tap
brew install --cask flexpa-health-bridge
```

Casks here are generated by the release workflow in
[flexpa/bridge](https://github.com/flexpa/bridge); send changes there, not here.
READme
    mkdir -p Casks
    git add -A
    git -c user.name="flexpa-bot" -c user.email="engineering@flexpa.com" commit -qm "chore: seed the tap"
    git branch -M master
    git remote add origin "https://github.com/$TAP.git"
    git push -q -u origin master
  )
  rm -rf "$WORK/seed"
fi

echo "▸ updating the cask to $VERSION"
git clone -q "https://github.com/$TAP.git" "$WORK/tap"
mkdir -p "$WORK/tap/Casks"
sed -e "s/__VERSION__/$VERSION/" -e "s/__SHA256__/$SHA256/" \
  "$ROOT/Packaging/homebrew/flexpa-health-bridge.rb" > "$WORK/tap/Casks/flexpa-health-bridge.rb"

cd "$WORK/tap"
if git diff --quiet; then
  echo "  cask already at $VERSION, nothing to push"
  exit 0
fi
git add Casks/flexpa-health-bridge.rb
git -c user.name="flexpa-bot" -c user.email="engineering@flexpa.com" \
  commit -qm "flexpa-health-bridge $VERSION"
git push -q origin HEAD
echo "✓ $TAP now serves flexpa-health-bridge $VERSION"
